# 完全なXPath指定＋新規レコード以外のページのスクリーンショット
# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.chrome.options import Options
import time
from bs4 import BeautifulSoup
import re
from selenium.webdriver.common.keys import Keys
from Screenshot import Screenshot
import os


class TestAddNewRecord_ver2_1():
  def setup_method(self, method):
    options = Options()
    # options.add_argument('--headless')  # ヘッドレスモードでブラウザを起動
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    self.driver = webdriver.Remote(command_executor='http://chrome:4444/wd/hub', options=options)
    self.driver.implicitly_wait(10) # 10秒まで待機する
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addNewRecord(self):
    img_folder = os.path.join(os.path.dirname(os.path.abspath(__file__)), "img")
    ob = Screenshot.Screenshot()
    counter = 1
    image_name_seq = f'a{counter}.png'

    self.driver.get("https://saruya:saruya@staging-user.photolize.jp/login/basic_auth")
    self.driver.get("https://staging-user.photolize.jp/login")
    self.driver.set_window_size(1463, 1032)
    # 追加: ここでフルページのスクリーンショットを取る  
    ob.full_screenshot(self.driver, save_path=img_folder, image_name=image_name_seq) 
    counter += 1
    image_name_seq = f'a{counter}.png'
    self.driver.find_element(By.ID, "input-7").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".v-btn__content")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.ID, "input-7").send_keys("company_code26")
    self.driver.find_element(By.CSS_SELECTOR, ".v-btn__content").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.ID, "input-11").send_keys("aridome")
    self.driver.find_element(By.ID, "input-14").send_keys("aridome")
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn > .v-btn__content")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".btn > .v-btn__content").click()
    # 追加: ここでフルページのスクリーンショットを取る  
    ob.full_screenshot(self.driver, save_path=img_folder, image_name=image_name_seq) 
    counter += 1
    image_name_seq = f'a{counter}.png'
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".py-0:nth-child(2) .relative")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.execute_script("window.scrollTo(0,317)")
    element = self.driver.find_element(By.CSS_SELECTOR, ".py-0:nth-child(12) .v-list-item__title")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".py-0:nth-child(12) .v-list-item__title").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.LINK_TEXT, "新規レコード追加").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".input").click()
    element = self.driver.find_element(By.XPATH, "/html/body/div/div[2]/div[6]/div/div/div[1]/div/span/span/div/div/div[1]/div/input")
    self.driver.execute_script("arguments[0].click();", element)
    element = self.driver.find_element(By.CSS_SELECTOR, ".v-dialog__content:nth-child(6) .v-card__actions .v-btn__content")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.XPATH, "/html/body/div/div[2]/div[6]/div/div/div[1]/div/span/span/div/div/div[1]/div/input")
    # キーボードのショートカットで入力内容を全選択
    element.send_keys(Keys.CONTROL + "a")
    # キーボードのショートカットで入力内容を削除
    element.send_keys(Keys.DELETE)
    element.send_keys("お寿司")
    self.driver.find_element(By.CSS_SELECTOR, ".v-dialog__content:nth-child(6) .v-card__actions .v-btn__content").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".checkbox").click()
    # モーダル画面が表示されるまで少し待機
    time.sleep(0.5)
    self.driver.execute_script("window.scrollTo(0,200)")
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) .cbbox").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) .cbbox")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) .cbbox").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".v-dialog__content:nth-child(16) .v-card__actions .v-btn__content")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".v-dialog__content:nth-child(16) .v-card__actions .v-btn__content").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".radio").click()
    # モーダル画面が表示されるまで少し待機
    time.sleep(0.5)
    self.driver.find_element(By.CSS_SELECTOR, ".v-radio:nth-child(3) .v-input--selection-controls__ripple").click()
    self.driver.find_element(By.CSS_SELECTOR, ".v-dialog__content:nth-child(10) .v-card__actions .v-btn__content").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".v-btn--is-elevated > .v-btn__content")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".v-btn--is-elevated > .v-btn__content").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".theme--light:nth-child(2) > .v-btn__content")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".theme--light:nth-child(2) > .v-btn__content").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".v-card__actions:nth-child(2) .v-btn__content")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".v-card__actions:nth-child(2) .v-btn__content").click()
        # 追加: ここでフルページのスクリーンショットを取る  
    ob.full_screenshot(self.driver, save_path=img_folder, image_name=image_name_seq) 
    counter += 1
    image_name_seq = f'a{counter}.png'
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".v-avatar > img")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".v-avatar > img").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".v-btn--text")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".v-btn--text").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.close()
  
