# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestA():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://chrome:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_a(self):
    self.driver.get("https://staging-admin.photolize.jp/admin")
    self.driver.set_window_size(1936, 1168)
    self.driver.find_element(By.LINK_TEXT, "アプリ一覧を見る").click()
    self.driver.find_element(By.LINK_TEXT, "有留テストアプリ").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".v-btn:nth-child(9)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".mdi-content-save").click()
    assert self.driver.switch_to.alert.text == "保存しました"
  
